---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-enterprise-search-sharepoint-server-connector
  description: Buildkite Pipeline for enterprise-search-sharepoint-server-connector
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/enterprise-search-sharepoint-server-connector

spec:
  type: buildkite-pipeline
  owner: group:ingestion-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: enterprise-search-sharepoint-server-connector
    spec:
      repository: elastic/enterprise-search-sharepoint-server-connector
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        # your-team:
        #  access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
